# Generated by Django 4.1.2 on 2022-11-21 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BASIC_DATA',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=200)),
                ('mother_name', models.CharField(default='', max_length=200)),
                ('about_you', models.TextField()),
                ('profile', models.FileField(upload_to='profile_images/')),
            ],
        ),
    ]
