# Generated by Django 4.1.2 on 2022-11-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basic_data',
            name='profile',
            field=models.ImageField(upload_to='media/profile_images'),
        ),
    ]
